# This docker-compose.yml file is not intended for production, but for development!
version: "3.5"

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

  api:
    build:
      context: .
      target: development
    command: npm run watch
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - ".:${INSTALL_PATH:-/usr/src/api}"
    env_file:
      - ".env"
    depends_on:
      - mongodb
