version: "3.5"

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src/api"
    env_file:
      - ".env"
    depends_on:
      - mongodb
